branch create new (before make fork not supported)

diff --git a/bin/branch b/bin/branch
--- a/bin/branch
+++ b/bin/branch
@@ -1,5 +1,12 @@
 #!/usr/bin/env bash
 
+#set -x
+################################ LIBRARIES SHARED OVER ALL CW SCRIPTS ################################
+globals=()
+. $(dirname $0)/lib/shared_functions.sh
+
+
+################################ BRANCH-SPECIFIC HELP ################################
 function show_help() {
 cat << EOF
 
@@ -8,7 +15,7 @@ NAME:
 
 SYNOPSIS:
     ${0##*/} [--view] [--[no-]sync] [--[no-]push [<remote>]]
-    ${0##*/} [[--fallback <branch1> ...]
+    ${0##*/} [[--fallback <branch1> ...] [--[no-]umbrella]
                     [--[no-]push] new-branch [<fork-branch>] -- <repo>[:<fork-branch> ...
     ${0##*/}  --delete|-d|-D branch [--[no-]push [<remote>]]
 
@@ -39,10 +46,13 @@ OPTIONS:
           if possible. By default --sync is not performed
 
       --fallback[=| ]<branch>
-          if submodule already has new creating branch, it just checking to it out and
+          fallback branch name used instead of <fork-branch>, if last does not exists in sub-module
 
       --[no-]push[=<remote>]
-          push to remote (origin by default) repository.
+          push (or prevent) to <remote> ('origin' by default) repository.
+
+      --
+          marks state after which only affected repositories will be enumerated. If --[no-]umbrella option is given
 
 EOF
 }
@@ -51,16 +61,24 @@ typeset doView=0
 typeset doSync=1
 typeset doAutoCommit=1
 typeset doPush=0
+typeset stopOptions=0
+typeset doUpdate=0
+typeset doUmbrella=1
+typeset branchName
+typeset forkName
+
 (( ! $# )) && doView=1; doSync=0; doPush=0; doAutoCommit=0
 
 # globals is being used in consistent_bootstrap as container return important metrics of branded repo
 
-globals=()
-args=()
 fallbacks=()
 repos=()
+excludes=()
 
+################################ PARAMETERS PARSING ################################
 while [[ -n $1 ]]; do
+  afterOptions=${1%%--*}
+  (( $stopOptions )) && [[ -z $afterOptions ]] && die "after '--' additional options are not allowed "
   case $1 in
     -h|-\?|--help)
       show_help
@@ -84,20 +102,20 @@ while [[ -n $1 ]]; do
       exit 1
       ;;
 
-    --repo)
+    --exclude)
       if [ -n "$2" ]; then
-        ${repos[${#repos[@]}]}=$2
+        ${excludes[${#excludes[@]}]}=$2
         shift
       else
-        cw_echo 'ERROR: "--repo" requires a non-empty option argument.' >&2
+        cw_echo 'ERROR: "--exclude" requires a non-empty option argument.' >&2
         exit 1
       fi
       ;;
-    --repo=?*)
-      ${repos[${#repos[@]}]}=${1#*=} # Delete everything up to "=" and assign the remainder.
+    --exclude=?*)
+      ${excludes[${#excludes[@]}]}=${1#*=} # Delete everything up to "=" and assign the remainder.
       ;;
-    --repo=)         # Handle the case of an empty --repo=
-      cw_echo 'ERROR: "--repo" requires a non-empty option argument.' >&2
+    --exclude=)         # Handle the case of an empty --exclude=
+      cw_echo 'ERROR: "--exclude" requires a non-empty option argument.' >&2
       exit 1
       ;;
 
@@ -106,6 +124,13 @@ while [[ -n $1 ]]; do
       ;;
     --no-push)
       doPush=0
+      ;;
+
+    --umbrella)
+      doUmbrella=1
+      ;;
+    --no-umbrella)
+      doUmbrella=0
       ;;
 
     --sync)
@@ -123,6 +148,9 @@ while [[ -n $1 ]]; do
       doAutoCommit=0
       ;;
 
+    -v|--verbose)
+        verbose=$((verbose + 1)) # Each -v argument adds 1 to verbosity.
+        ;;
     --view)
       doView=1
       ;;
@@ -131,11 +159,19 @@ while [[ -n $1 ]]; do
       doDelete=1
       ;;
 
+    --)
+      stopOptions=1
+      ;;
     *)
-      if [[ -z ${branchName} ]]; then
-        branchName="$1"
-      elif [[ -z ${forkName} ]]; then
-        forkName="$1"
+      if (( ! $stopOptions )); then
+        if [[ -z ${branchName} ]]; then
+          branchName="$1"
+          doUpdate=1
+        elif [[ -z ${forkName} ]]; then
+          forkName="$1"
+        fi
+      else
+        repos[1+${#repos[@]}]="$1"
       fi
       ;;
   esac
@@ -143,7 +179,7 @@ while [[ -n $1 ]]; do
 done
 
 
-. $(dirname $0)/lib/shared_functions.sh
+################################ STANDARD BOOTSTRAP CALL ################################ 
 
 skipSplash=1
 consistentwork_bootstrap
@@ -222,7 +258,7 @@ function check_branch_sync() {
       git diff --exit-code --quiet -- .gitmodules
       needToCommit=$?
       #echo "needToCommit=${needToCommit}"
-      if (( $needToCommit )); then
+      if (( $qeedToCommit )); then
         if (( $doAutoCommit )); then
           git add .gitmodules
           git commit -m "$subRepoName submodule configuration is changed"
@@ -234,19 +270,29 @@ function check_branch_sync() {
   done < <(git config -f .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")
 
   return "${ret}"
-}
+} ## of check_branch_sync
+
+
+cd "${cwRoot}"
+  ##
+  ## Current state of umbrella branch
+  ##
+mainBranch=$(git rev-parse --abbrev-ref HEAD)
+  ##
+  ## Exit code of the script
+  ## 0 - success
+  ## 1 - warning
+  ## 2 - error
+  ##
+declare ret=0
 
 if (( "$doView" )); then
+############################################### CHECK STATE (SHOW) (VIEW) ################################################
   #printf "do view"
   #(( $doSync )) && printf ", do sync"; (( $doAutoCommit )) && printf "(autocommit)"; (( ! $doAutoCommit )) && printf "(NO autocommit)"; (( ! $doSync )) && printf ", NO sync"
   #(( $doPush )) && printf ", do push";  (( ! $doPush )) && printf ", NO push"
 #  printf "\n"
 
-
-  declare ret=0
-
-  cd "${cwRoot}"
-  mainBranch=$(git rev-parse --abbrev-ref HEAD)
   if [[ ${mainBranch} == "HEAD" ]]; then
     instruction="$(cat<<EOF
 Umbrella repo is in the detached mode.
@@ -255,6 +301,7 @@ Umbrella repo is in the detached mode.
 EOF
 )"
     cw_echo "${instruction}"
+    ret=1
   else
     cw_echo "Umbrella repo at '$mainBranch' branch"
   fi
@@ -262,8 +309,47 @@ EOF
   check_branch_sync "${cwRoot}"
   ret=$?
 
-  [[ 0 == $ret && -z ${instruction} ]] && cw_echo "All submodules are mutually syncronized."
+  (( ! $ret )) && cw_echo "All submodules are mutually syncronized."
   [[ $ret == 1 ]] && cw_echo "Submodules are not synchronized. Run '${0##*/} --sync' to fix"
+  [[ $ret == 2 ]] && cw_echo "Unexpected error"
 
-  exit $ret
+elif (( $doUpdate )); then
+################################################# UPDATE #################################################
+  currentUmbrellaState="'${mainBranch}'"
+  [[ $mainBranch == "HEAD" ]] && currentUmbrellaState="detached"
+
+  typeset mainAlreadyExists=$(is_branch_exists "${branchName}")
+  if (( $mainAlreadyExists )) && (( $doUmbrella )); then
+    die "Branch '$branchName' already exists in the umbrella repo.
+        You are adviced to do   'checkoout $branchName'
+        and then continue to create branch in sub-repositories with '${0##*/} ... --no-umbrella ...' option"
+  fi
+
+  typeset
+
+  if (( $doUmbrella )); then
+    cw_echo "About to create new branch '$branchName' for umbrella repo" \
+      "Current umbrella branch: $currentUmbrellaState" \
+      "Fork branch name: '$forkName'" \
+      "Affected repos: '${repos[*]}'" \
+      "Fallback branches: '${fallbacks[*]}'"
+  else
+    cw_echo "About to create branch '$branchName' in sub-repositories"
+  fi
+
+  if [[ -n $forkName && $mainBranch != $forkName ]]; then
+    if (( $doUmbrella )); then
+      # TODO check whether $forkName exist or not, if not - check whether fallback branch exists
+      cd "${cwRoot}"
+      typeset forkExists = $(is_branch_exists "${forkName}")
+      if (( $forkExists )); then
+        cw_echo "Change branch for umbrella from '$mainBranch' to '$forkName'"
+        git checkout "${forkName}"
+      fi
+    fi
+  fi
 fi
+
+
+cw_verbose_stop
+exit $ret
