git lego instead umbrella started
Join mfs.sh & shared_functions.sh into git-lego.
Because of weird error 'No such file or directory' by process substitution issue

diff --git a/bin/git-lego-clone b/bin/git-lego-clone
--- a/bin/git-lego-clone
+++ b/bin/git-lego-clone
@@ -4,8 +4,20 @@ typeset repoUrl=$1
 typeset repoPath=$2
 
 
-declare -a globals
-declare -a args="$@"
+usage() {
+  cat << EOF
+    usage: git lego clone <any-legal-arguments for git clone>
+EOF
+}
+
+#. $(dirname $0)/lib/mfs.sh
+#. $(dirname $0)/lib/shared_functions.sh
+
+
+cmd_default() {
+
+#declare -a globals
+#declare -a args="$@"
 ################################ LIBRARIES SHARED OVER ALL CW SCRIPTS ################################
   #
   ## Exit code of the script
@@ -15,8 +27,7 @@ declare -a args="$@"
   #
 declare ret=0
 
-. $(dirname $0)/lib/mfs.sh
-. $(dirname $0)/lib/shared_functions.sh
+#set -x
 
 # Maybe we trying to cloning inside of the existing branding repo?
 # Right now it doesn't permitted
@@ -27,11 +38,23 @@ if (( ! $? )); then
   exit 0
 fi
 
-cw_echo "Will clone repository $repoUrl to $repoPath"
-git clone "$@"
+  cw_echo "Redirect to 'git clone'"
+  git clone "$@"
+  ret=$?
+#echo $ret
+
+if [[ ${repoUrl} == "--help" || -z ${repoUrl} ]]; then
+    exit 0
+fi
+
+
+if (( $ret )); then
+     die "Unrecoverable error by cloning"
+fi
+
 
 #set -x
-if [[ -z "${repoPath}" ]]; then
+if [[ ! -d "${repoPath}" ]]; then
   # no explicit destination repository given
   # take from last created directory
   for i in `ls -t1 | grep -v ^.$`; do
@@ -39,6 +62,7 @@ if [[ -z "${repoPath}" ]]; then
     break;
   done
 fi
+
 
 cd "$repoPath"
 
@@ -57,3 +81,12 @@ ret=$?
 
 umbrella_finalize
 exit ${ret}
+}
+
+cmd_help() {
+	usage
+	exit 0
+}
+
+
+#cmd_default "$@"
