progress with status; unmanged state; update

diff --git a/git-lego b/git-lego
--- a/git-lego
+++ b/git-lego
@@ -15,6 +15,11 @@ g_relative_paths=()
 g_git_dirs=()
 g_full_paths=()
 g_module_paths=()
+g_module_inited=()
+g_module_shas=()
+g_module_managed=()
+
+g_lego_aware_tokens=("branch" "pinned")
 
 globals=()
   ################################## CONSTANTS FOR globals array ##########################################
@@ -45,6 +50,7 @@ G_MODULES_FN=4
   #
 G_AFFECTED_MODULES=5
 
+G_LEGO_REMOTE=6
 
 
 #################### CONSTANTS for MODULE STATUS (see function module_porcelain_status() ####################
@@ -93,12 +99,14 @@ MFS_GIT_DIR=2
 MFS_FULL_PATH=3
 MFS_MODULE_PATH=4
 MFS_MODULE_INITIALIZED=5
-
+MFS_MODULE_SHA=6
+MFS_MODULE_MANAGED=7
 
 
 # set this to workaround expr problems in shFlags on freebsd
 #if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi
 
+typeset g_lego_mode
 
 umbrella_bootstrap (){
   legoRemote=$(get_submodule_config "lego.remote")
@@ -124,9 +132,10 @@ umbrella_bootstrap (){
 #  rm ${cwTmpSubmodules} &>/dev/null
   pushd ${umbrellaRepoDir} &>/dev/null
 
+
 #  local remoteOrigin=$(git remote show)
   local umbrellaOriginUrl umbrellaRepoName
-  if [[ -n $remoteOrigin ]]; then
+  if [[ -n ${legoRemote} ]]; then
     local url=$(get_repo_url "$umbrellaRepoDir")
 
     umbrellaOriginUrl=$(git remote get-url "${legoRemote}")
@@ -147,9 +156,20 @@ umbrella_bootstrap (){
   globals[$G_ROOT_DIR]=${umbrellaRepoDir}
   globals[$G_MODULE_GIT_DIR]=${gitDir}
   globals[$G_ROOT_NAME]=${umbrellaRepoName}
-  module_startup_investigate "${umbrellaRepoName}" "/" ".git" "${umbrellaRepoDir}" "/" 1
+  local sha=$( git rev-parse HEAD )
+
+  ##
+  local implicit
+  read g_lego_mode implicit < <(get_lego_mode 1)
+#  echo $g_lego_mode ${implicit:-2}
+
+  module_startup_investigate "${umbrellaRepoName}" "/" ".git" "${umbrellaRepoDir}" "/" 1 "${sha}" 1
+#  cat ${globals[$G_MODULES_FN]} >&2
+#  echo ${g_module_name[@]} >&2
+#  echo ${g_module_inited[@]} >&2
+#  echo ${g_module_managed[@]} >&2
   popd &>/dev/null
-  splash ${umbrellaRepoName}
+  splash ${umbrellaRepoName} ${implicit}
 
   return 0
 }
@@ -158,19 +178,24 @@ umbrella_bootstrap (){
 function module_startup_investigate() {
   local tmpModules=${globals[$G_MODULES_FN]}
   echo "$@">>${tmpModules}
-  # map emulation for quick access of the
+  # keep all module descriptors' values in the global arrays for cached access
+  # basically they will be used in 'module_info' method
   g_module_name+=($1)
   g_relative_paths+=($2)
   g_git_dirs+=($3)
   g_full_paths+=($4)
   g_module_paths+=($5)
+  g_module_inited+=($6)
+  g_module_shas+=($7)
+  g_module_managed+=($8)
 
   while read -a module
   do
     local subModule="${module[MFS_MODULE_NAME]}"
     local localPath="${module[MFS_RELATIVE_PATH]}"
     local is_initialized=1
-    local moduleStatus=$(git submodule status -- ${subModule})
+    local moduleStatus=($(git submodule status -- ${subModule}))
+    local managed=$(resolve_module_managed "${localPath}" "${subModule}") #get_lego_setting_at_mode
 
     pushd ${localPath} &> /dev/null
     module+=($(get_repo_git_dir))             # MFS_GIT_DIR=2
@@ -184,7 +209,14 @@ function module_startup_investigate() {
     if [[ ${moduleStatus:0:1} == "-" ]]; then
       is_initialized=0
     fi
-    module+=(${is_initialized})
+    module+=(${is_initialized})               #MFS_MODULE_INITIALIZED=5
+    local statusLine=("${moduleStatus}")
+    local sha=${statusLine[0]}
+    if [[ ${sha:0:1} == - ]]; then
+      sha=${sha:1}
+    fi
+    module+=(${sha})                          # MFS_MODULE_SHA 6
+    module+=("${managed}")                    # MFS_MODULE_MANAGED 7
 
     module_startup_investigate ${module[@]}
     popd &> /dev/null
@@ -258,7 +290,9 @@ function cw_verbose_stop () {
 function splash() {
   (( $skipSplash )) && return
   local url=$1
-  local msg="umbrella repo: "${url}
+  local implicit=$2
+  local msg="umbrella repo: "${url}", lego mode: $g_lego_mode"
+  (( $implicit )) && msg+=" (guessed)"
   local currentGitDir=$(get_repo_git_dir)
   local currentRepoName=${currentGitDir##*/modules/}
   [[ -n ${currentRepoName} && ${url} != ${currentRepoName} && $currentGitDir != ".git" ]] && msg+=", current module '"${currentRepoName}"'"
@@ -509,6 +543,15 @@ function module_info () {
       gitdir)
         results+=(${g_git_dirs[$index]})
         ;;
+      sha)
+        results+=(${g_module_shas[$index]})
+        ;;
+      initialized)
+        results+=(${g_module_inited[$index]})
+        ;;
+      managed)
+        results+=(${g_module_managed[$index]})
+        ;;
       *)
         ret=2
         break
@@ -521,7 +564,26 @@ function module_info () {
 }
 
 
-function is_repo_initialized() {
+
+function is_module_managed() {
+  local levelPath=$1
+  local ret=0
+  [[ -z ${levelPath} ]] && panic "$FUNCNAME()... parameter 'path' is required"
+
+  while read -a module; do
+    local fullPath=${module[${MFS_FULL_PATH}]}
+    if [[ ${levelPath} == ${fullPath} && ${module[7]} == 1 ]]; then
+      ret=1
+      break
+    fi
+  done < <(cat ${globals[${G_MODULES_FN}]})
+
+  echo ${ret};
+  return ${ret}
+}
+
+
+function is_module_initialized() {
   local levelPath=$1
   local ret=0
   [[ -z ${levelPath} ]] && panic "$FUNCNAME()... parameter 'path' is required"
@@ -538,11 +600,13 @@ function is_repo_initialized() {
   return ${ret}
 }
 
+
 function is_branch_exists() {
   [[ -z $1 ]] && (panic "'branch' argument for is_branch_exists() should be given")
   local branchName=$1
   local where=$2
   local checkedSites=("", "origin")
+  local ret=0
   if [[ -n $where ]]; then
     # TODO
     die "'where' parameter for is_branch_exists() not implemented yet"
@@ -552,19 +616,20 @@ function is_branch_exists() {
     (( ${#prefix} )) && prefix+="/"
     git rev-parse --no-revs "${prefix}${branchName}" &>/dev/null
     local ret=$?
+
+    # inverting
     if (( ! $ret )); then
       ret=1
     else
       ret=0
-    fi
-    if (( $ret )); then
-     break
+      break
     fi
   done
 
   echo ${ret}
   return ${ret}
 }
+
 
 typeset MODULE_STATUS=()
 #
@@ -576,31 +641,36 @@ typeset MODULE_STATUS=()
 #
 ## Parameters
 #     $1  - mode, which indicated the caller script, ie. "status"/"commit"/..
-#     $2  - path of current module
+#     $2  - file path of current module
 #     ... - other parameters relevant to its caller
 #       For 'status' mode
-#           $3 - module is initialized (1/0)
-#           $4 - stick-on-branches, branch which outer module expects inner module to be
+#           $3 - stick-on-branches, branch which outer module expects inner module to be
 #
 ## Globals affected
 #     $MODULE_STATUS array
 #
 function module_porcelain_status() {
-#echo "$FUNCNAME() mode: $1, modulePath: $2, initialized: $3, stickOnBranch: $4"
+#echo "$FUNCNAME() mode: $1, modulePath: $2, stickOnBranch: $3"
+
+  #########
+  ######## TODO migrate to --porcelain=2
+  #########
   local remoteInteraction=0 stickOnBranch guessedBranched=()
 
   [[ $1 == "push" || $1 == "pull" ]] && remoteInteraction=1
 
+#set -x
   unset MODULE_STATUS
   local modulePath="$2"
-  local initialized="$3"
-  local stickOnBranch="$4"
-
+  local stickOnBranch="$3"
+#  local moduleName="$5"
+  read initialized managed < <(module_info ${modulePath} initialized managed )
+#set +x
   # TODO take care about ambiguous references like master & tags/master
   test -n ${stickOnBranch} && MODULE_STATUS[$MS_INNER_REV_HINT]=${stickOnBranch}
 
 #  set -x
-  if (( ${initialized} )) || [[ ${modulePath} == / ]] ; then
+  if [[ ${initialized} == 1 || ${modulePath} == / ]] ; then
     while read line; do
       # parse line into array or words
       local output=(${line})
@@ -617,7 +687,7 @@ function module_porcelain_status() {
               MODULE_STATUS[$MS_INCONSISTENT]=1
               MODULE_STATUS[$MS_GUESSED_BRANCHES]="${guessedBranched}"
             fi
-            MODULE_STATUS[$MS_BRANCH_INFO]="${output[@]:1}"
+            MODULE_STATUS[$MS_BRANCH_INFO]="${output[1]}"
           fi
           # TODO will not working in locale differs form en_US (or en_XX)
           # TODO git rev-list --count can help?
@@ -628,6 +698,9 @@ function module_porcelain_status() {
           fi
           ;;
         *)
+#          if [[ "${output[1]}" == "${moduleName}" ]]; then
+#            #instead of file add
+#          fi
           local fChar=${line:0:1} sChar=${line:1:1}
           [[ ${fChar} == "?" ]] && MODULE_STATUS[$MS_UNTRACKED]=$(( MODULE_STATUS[$MS_UNTRACKED] + 1 ))
           [[ ${fChar} == M || ${sChar} == M ]] && MODULE_STATUS[$MS_MODIFIED]=$(( MODULE_STATUS[$MS_MODIFIED] + 1 )) ; MODULE_STATUS[$MS_COMMITABLE]=1
@@ -1214,12 +1287,41 @@ get_submodule_config () {
 	name="$1"
 	option="$2"
 	default="$3"
-	value=$(git config submodule."$name"."$option")
+	value=$(git config --get submodule."$name"."$option" &>/dev/null)
 	if test -z "$value"
 	then
-		value=$(git config -f .gitmodules submodule."$name"."$option")
+		value=$(git config -f .gitmodules --get submodule."$name"."$option" &>/dev/null)
 	fi
 	printf '%s' "${value:-$default}"
+}
+
+resolve_module_managed() {
+  local module_name=$1
+  local module_path=$2
+  local mode="${3:-$g_lego_mode}"
+  local ret=0
+  for token in "${g_lego_aware_tokens[@]}" ; do
+    local key="${module_name}.${token}"
+    local value=$(get_lego_setting_at_mode "${key}" "submodule" "${mode}")
+
+    [[ -n ${value} ]] && ret=1 ; break
+  done
+  echo ${ret}
+}
+
+
+get_lego_setting_at_mode() {
+  local key=$1
+  local section=$2
+  local mode=${3:-${g_lego_mode}}
+  local value
+
+  if [[ ${mode} == solo ]] ; then
+    value=$( get_lego_setting_concrete "$1" "${section}" )
+  else
+    value=$( get_lego_setting_concrete "$1" "${section}" "-f .gitmodules" )
+  fi
+  echo "$value"
 }
 
 
@@ -1236,6 +1338,7 @@ get_lego_setting() {
 
 ##
 get_lego_setting_concrete() {
+#pwd >&2
   local key="$1"
   [[ -z $key ]] && panic "$FUNCNAME() missing setting name"
   local file_option="${3---}"
@@ -1248,22 +1351,32 @@ get_lego_setting_concrete() {
     unset file_option
   fi
 
-  echo $(git config ${file_option} --get "${section:+$section.}$key") 2>/dev/null
+  echo $(git config ${file_option} --get "${section}.$key") 2>/dev/null
 }
 
+
+##
 get_lego_mode() {
+  local verbose=$1
   local mode=$( get_lego_setting "mode")
+  local implicit=0
+  local results=()
   if [[ -z "$mode" ]] ; then
     mode=$( investigate_lego_mode )
+    implicit=1
   fi
-  echo ${mode}
+  results+=("$mode")
+  if [[ $verbose == 1 ]] ; then
+    results+=("${implicit}")
+  fi
+  echo ${results[@]}
 }
 
 investigate_lego_mode() {
-#  echo $FUNCNAME
   local mode
   local ambiguous
   local value
+  local cwRoot="${globals[$G_ROOT_DIR]}"
 
   pushd ${cwRoot} &> /dev/null
   if [[ -e "$cwRoot/.gitlego" ]] ; then
@@ -1274,7 +1387,7 @@ investigate_lego_mode() {
 
     while read module path; do
       if [[ $(get_lego_setting_concrete "${module}.branch" "submodule" "-f .gitmodules") ]]; then
-        if (( $( check_ambiguous_mode versioned ${mode} ) )) ; then
+        if (( $( check_ambiguous_lego_mode versioned ${mode} ) )) ; then
           mode=ambiguous
         else
           mode=versioned
@@ -1285,7 +1398,7 @@ investigate_lego_mode() {
 
     while read module value; do
       if [[ $value == true ]] && [[ $(get_lego_setting_concrete "${module}.branch" "submodule" "--local") ]]; then
-        if (( $( check_ambiguous_mode solo ${mode} ) )) ; then
+        if (( $( check_ambiguous_lego_mode solo ${mode} ) )) ; then
           mode=ambiguous
         else
           mode=solo
@@ -1295,7 +1408,7 @@ investigate_lego_mode() {
     done < <(git config --get-regexp "submodule.*.active" | sed -E "s/submodule\.(.*)\.active/\1/")
 
   #else
-  #   TODO if no .gitmodules file -> no submodule -> git-lego ambigious
+  #   TODO if no .gitmodules file -> no submodule -> git-lego ambigious ??
   #
   fi
 
@@ -1303,7 +1416,7 @@ investigate_lego_mode() {
   echo "${mode:-empty}"
 }
 
-check_ambiguous_mode() {
+check_ambiguous_lego_mode() {
   local val=$1
   local prevVal=$2
   if [[ -n $prevVal ]] && [[ $val != $prevVal ]] ; then
@@ -1372,12 +1485,12 @@ main() {
 	SUBACTION="default"
 
 	# Particular script can figure out a specific action depends on arguments or other circumstances.
-	# In this case it should define what_sub_action function and echo'ing required action.
-	# If what_sub_action returns empty string - default is using
-	if type "what_sub_action" >/dev/null 2>&1; then
-		local customized=$(what_sub_action "$@")
-		if [[ -n ${customized} ]]; then
-		  SUBACTION=${customized}
+	# In this case it should define dispatch_subaction function and echo'ing required action.
+	# If dispatch_subaction returns empty string - default is using
+	if type "dispatch_subaction" >/dev/null 2>&1; then
+		local dispatched=$(dispatch_subaction "$@")
+		if [[ -n ${dispatched} ]]; then
+		  SUBACTION=${dispatched}
 		fi
 	fi
 
@@ -1389,6 +1502,5 @@ main() {
 
   cmd_$SUBACTION "$@"
 }
-
 
 main "$@"
