continue with git-lego

diff --git a/git-lego b/git-lego
--- a/git-lego
+++ b/git-lego
@@ -1,5 +1,4 @@
 #!/usr/bin/env bash
-#
 
   # After call to 'umbrella_bootstrap' this array contains following predefined values.
   #
@@ -75,10 +74,7 @@ MFS_MODULE_PATH=4
 
 
 # set this to workaround expr problems in shFlags on freebsd
-#if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi
-
-. $(dirname $0)/lib/mfs.sh
-#. $(dirname $0)/lib/shared_functions.sh
+if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi
 
 
 function umbrella_bootstrap () {
@@ -180,6 +176,9 @@ function umbrella_finalize() {
   rm -rf ${globals[$G_SCRIPT_TMP_DIRECTORY]}
   _m_finalize
 }
+
+warn() { echo "$@" >&2; }
+#die() { warn "$@"; exit 1; }
 
 function die() {
   local msg="$1"
@@ -1133,17 +1132,6 @@ main() {
 	# Linux platforms.
 	export POSIXLY_CORRECT=1
 
-	# use the shFlags project to parse the command line arguments
-	. "$GITLEGO_DIR/gitlego-shFlags"
-#	FLAGS_PARENT="git lego"
-
-  # allow user to request git action logging
-#  DEFINE_boolean show_commands false 'show actions taken (git commands)' g
-
-  # do actual parsing
-#	FLAGS "$@" || exit $?
-#	eval set -- "${FLAGS_ARGV}"
-
 	# sanity checks
 	local SUBCOMMAND="$1"; shift
 
@@ -1154,26 +1142,28 @@ main() {
 
 	# run command
 	. "$GITLEGO_DIR/git-lego-$SUBCOMMAND"
-#	FLAGS_PARENT="git lego $SUBCOMMAND"
 
-	# test if the first argument is a flag (i.e. starts with '-')
-	# in that case, we interpret this arg as a flag for the default
-	# command
+
 	SUBACTION="default"
-	if [[ "$1" == "" ]] && { ! echo "$1" | grep -q "^-"; }
-	then
-		SUBACTION="$1"; shift
+
+	# Particular script can define a specific action depends on arguments.
+	# In this case it should define cmd_sub_action function and echo'ing required action.
+	# If cmd_sub_action returns empty string - default is using
+	if type "cmd_sub_action" >/dev/null 2>&1; then
+
+		local customized=$(cmd_sub_action "$@")
+		if [[ -n $customized ]]; then
+		  SUBACTION=$(cmd_sub_action "$@")
+		fi
+
 	fi
+
 	if ! type "cmd_$SUBACTION" >/dev/null 2>&1; then
 		warn "Unknown subcommand: '$SUBACTION'"
 		usage
 		exit 1
 	fi
 
-	# run the specified action
-#  if [ $SUBACTION != "help" ] && [ $SUBCOMMAND != "init" ] ; then
-#    init
-#  fi
   cmd_$SUBACTION "$@"
 }
 
