status porcelain version 2 (started)

diff --git a/git-lego-status b/git-lego-status
--- a/git-lego-status
+++ b/git-lego-status
@@ -113,11 +113,10 @@ function show_current_module_status {
 #printf "%s,\n" "${MODULE_STATUS[@]}"
   local filePath="$1"
   local moduleName="$2"
-  oneLine="$3"                  # starting with module path
-  local initialized="$4"
-  local managed="$5"
-  local managedBranch="$6" # optional, can be null
+  local modulePath="$3"
   local verboseMsg=([1]="path: $filePath")
+
+  oneLine="$modulePath"
   verboseMsg+=("url: "$(get_repo_url))
 
   if (( $verbose )); then
@@ -125,17 +124,15 @@ function show_current_module_status {
   fi
 
   local verboseIssues infoIssues
-#  set -x
 
   # gather all additional fine information into $MODULE_STATUS global array
-  module_porcelain_status status ${oneLine} "${managedBranch}"
+  module_porcelain_status "${modulePath}" status
 
   # two below variables are defined to cmd_default()
   (( ${MODULE_STATUS[$MS_DETACHED]} )) && detached=${MODULE_STATUS[$MS_DETACHED]}
   (( ${MODULE_STATUS[$MS_COMMITABLE]} )) && commitable=${MODULE_STATUS[$MS_COMMITABLE]}
 
-  typeset branchInfo=${MODULE_STATUS[$MS_BRANCH_INFO]}
-#  local statusLine
+  local branchInfo=${MODULE_STATUS[$MS_BRANCH_INFO]}
   [[ -n ${branchInfo} ]] && [[ $branchInfo != HEAD ]] && oneLine+=", ${branchInfo}"
 
   if (( ${MODULE_STATUS[$MS_UNTRACKED]} )); then
@@ -145,7 +142,6 @@ function show_current_module_status {
   if (( ${MODULE_STATUS[$MS_ADDED]} )); then
     verboseIssues+="${verboseIssues:+ ,}added (${MODULE_STATUS[$MS_ADDED]} files)"
     infoIssues+="${infoIssues:+, }Ax${MODULE_STATUS[$MS_ADDED]}"
-
   fi
   if (( ${MODULE_STATUS[$MS_MODIFIED]} )); then
     verboseIssues+="${verboseIssues:+ ,}modified (${MODULE_STATUS[$MS_MODIFIED]} files)"
@@ -168,18 +164,48 @@ function show_current_module_status {
     infoIssues+="${infoIssues:+, }Ux${MODULE_STATUS[$MS_UNMERGED]}"
   fi
 
-
-#  set -x
   if (( ${MODULE_STATUS[$MS_UNINITIALIZED]} )); then
     oneLine+=", not initialized"
     verboseMsg+=("The module not initialized yet. 'git-lego init --reconcile' to fix it.")
-    print_managed_status ${managed}
+  fi
+
+  local mismatched=${MODULE_STATUS[$MS_MISMATCHED]}
+  local detached=${MODULE_STATUS[$MS_DETACHED]}
+  local managed=${MODULE_STATUS[$MS_MANAGED]}
+  local isOK=1
+#  if (( ${detached:-0} )) || (( ${mismatched:-0} )) || (( ! ${managed} )) ; then
+#    isOK=0
+#  fi
+
+  if (( ! $managed )) ; then
+    oneLine+=", unmanaged"
   else
+    oneLine+=", OK"
+  fi
+
+  if (( ! $isOK )) && [[ -n ${MODULE_STATUS[$MS_MANAGED_LINK]} ]]; then
+    oneLine+="${MODULE_STATUS[$MS_MANAGED_LINK]:+, expected:${MODULE_STATUS[$MS_MANAGED_LINK]}}"
+    verboseMsg+=("Expected, that module should be initialized to ${MODULE_STATUS[$MS_MANAGED_LINK]}")
+  fi
+
+  if (( ! ${MODULE_STATUS[$MS_UNINITIALIZED]} )); then
+
+    if [[ -n ${MODULE_STATUS[$MS_GUESSED_BRANCHES]} ]] && (( ${MODULE_STATUS[$MS_DETACHED]} )) ; then
+      oneLine+=", attainable to: ${MODULE_STATUS[$MS_GUESSED_BRANCHES]}"
+#        verboseMsg+=("Module has discrepancy between its current state and revision, which outer module expected")
+    fi
+
+    if (( ${#infoIssues} )) ; then
+      verboseIssues="issues: "$verboseIssues" paths"
+      verboseMsg+=("${verboseIssues}")
+      oneLine+=", dirty: "${infoIssues}
+    fi
+
     if (( ${MODULE_STATUS[$MS_DETACHED]} )); then
       oneLine+=", detached"
       verboseMsg+=("You need to run either 'git-lego checkout <branch-name>' or 'git-lego init [--reconcile|--pin]' to make those consent.")
-      if [[ -n $MODULE_STATUS[$MS_GUESSED_SHA] ]]; then
-        oneLine+=" @${MODULE_STATUS[$MS_GUESSED_SHA]}"
+      if [[ -n $MODULE_STATUS[$MS_MODULE_LINK] ]]; then
+        oneLine+=" @${MODULE_STATUS[$MS_MODULE_LINK]}"
         # TODO verboseMsg+=
       fi
     fi
@@ -192,20 +218,9 @@ function show_current_module_status {
 #        verboseMsg+=("Module has inconsistent state, outer module expects  ")
 #      fi
 #    fi
-    print_managed_status ${managed}
-    if [[ -n ${MODULE_STATUS[$MS_GUESSED_BRANCHES]} ]] && (( ${MODULE_STATUS[$MS_DETACHED]} )) ; then
-      oneLine+=", attainable to: ${MODULE_STATUS[$MS_GUESSED_BRANCHES]}"
-#        verboseMsg+=("Module has discrepancy between its current state and revision, which outer module expected")
-    fi
-
-    if (( ${#infoIssues} )) ; then
-      verboseIssues="issues: "$verboseIssues" paths"
-      verboseMsg+=("${verboseIssues}")
-      oneLine+=", dirty: "${infoIssues}
-    fi
   fi
   verboseMsg[0]=${oneLine}
-#  set +x
+
   cw_echo "${verboseMsg[@]}"
 
   if (( $verbose > 1 )) && [ -n ${args} ]; then
@@ -214,35 +229,13 @@ function show_current_module_status {
 }
 
 
-print_managed_status() {
-  local mismatched=${MODULE_STATUS[$MS_MISMATCHED]}
-  local detached=${MODULE_STATUS[$MS_DETACHED]}
-  local managed=${1}
-  local isOK=1
-  if (( ${detached:-0} )) || (( ${mismatched:-0} )) || (( ! ${managed} )) ; then
-    isOK=0
-  fi
-
-  if (( ! $managed )) ; then
-    oneLine+=", unmanaged"
-  else
-    oneLine+=", OK"
-  fi
-
-  if (( ! $isOK )) && [[ -n ${MODULE_STATUS[$MS_MANAGED_LINK]} ]]; then
-    oneLine+="${MODULE_STATUS[$MS_MANAGED_LINK]:+, expected:${MODULE_STATUS[$MS_MANAGED_LINK]}}"
-    verboseMsg+=("Expected, that module should be initialized to ${MODULE_STATUS[$MS_MANAGED_LINK]}")
-  fi
-}
-
 
 function status_level() {
   local levelPath="$1"
   [[ -z ${levelPath} ]] && panic "$FUNCNAME()... parameter 'path' is required"
   local repoBranch
-  local ret=0   # return code, 0 - the repo is syncronized
+  local ret=0   # return code, 0 - the repo is synchronized
   local childRet # child return code
-  local managedBranch
 
   drop_to_affected ${levelPath}
 
@@ -252,16 +245,8 @@ function status_level() {
     while read -a module; do
       childRet=0
       subModule="${module[0]}"
-      managedBranch=$(git config --file .gitmodules --get submodule."${subModule}".branch)
-      if [[ -z $managedBranch ]]; then
-        managedBranch=$(git config --file .gitmodules --get submodule."${subModule}".pinned)
-      fi
       localPath="${module[1]}"
-#      set -x
       subRepoPath=${levelPath}/${localPath}
-      initialized=$(is_module_initialized ${subRepoPath})
-      managed=$(is_module_managed ${subRepoPath})
-#      set +x
 
       pushd "${subRepoPath}" &> /dev/null
       local modulePath="$3" #/$subModule"
@@ -270,7 +255,7 @@ function status_level() {
       fi
       modulePath+="$subModule"
 
-      status_level "${subRepoPath}" "${subModule}" "${modulePath}" "${initialized}" "${managed}" "${managedBranch}"
+      status_level "${subRepoPath}" "${subModule}" "${modulePath}"
       childRet=$?
       if [[ ${childRet} > ${ret} ]] ; then
         ret=${childRet}
@@ -278,6 +263,7 @@ function status_level() {
       popd  &> /dev/null
     done < <(git config -f .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")
   fi
+
   return $ret
 }
 
@@ -289,14 +275,12 @@ cmd_default() {
   local commitable
   local detached
 
-#  set -x
   local modulePath=$(resolve_module_path "${initialPath}" /)
   read moduleName path < <(module_info "${modulePath}" "name" "path")
 
   pushd ${path} &>/dev/null
   #baseModulePath=$(_m_pmd)
   status_level "${path}" "${moduleName}" "${modulePath}"
-#  set +x
   ret=$?
 
   if (( $commitable )); then
