progress with config --lego-mode; improvements in status

diff --git a/git-lego b/git-lego
--- a/git-lego
+++ b/git-lego
@@ -337,7 +337,7 @@ function level_verbose_about_to {
 #     2 - N/A module is not found or wrong argument
 #
 # Globals using
-#     $afterDash - array contains module list after double dash
+#     $afterDash - array, which contains restricted module list, can be given after double dash or some other manner
 #     $affected  - this variable should be defined outside of this function (output variable)
 #
 # TODO take into account --recursive flag
@@ -379,6 +379,26 @@ function drop_to_affected() {
   done < <(cat ${globals[$G_MODULES_FN]})
 
   return ${ret}
+}
+
+function module_descriptor() {
+  local levelPath=$1
+  local found=0
+
+  while read -a module; do
+    found=0
+    local moduleName=${module[$MFS_MODULE_NAME]}
+    local fullPath=${module[MFS_FULL_PATH]}
+    if [ "$levelPath" == "$fullPath" ]; then
+      found=1
+    fi
+
+    if (( ${found} )); then
+      echo ${module[@]}
+      break
+    fi
+
+  done < <(cat ${globals[$G_MODULES_FN]})
 }
 
 
@@ -566,8 +586,8 @@ typeset MODULE_STATUS=()
 #     $MODULE_STATUS array
 #
 function module_porcelain_status() {
-#module_porcelain_status status $modulePath "${initialized}" "${stickOnBranch}"
-  local remoteInteraction=0 stickOnBranch guessedBranched
+#echo "$FUNCNAME() mode: $1, modulePath: $2, initialized: $3, stickOnBranch: $4"
+  local remoteInteraction=0 stickOnBranch guessedBranched=()
 
   [[ $1 == "push" || $1 == "pull" ]] && remoteInteraction=1
 
@@ -586,20 +606,19 @@ function module_porcelain_status() {
       local output=(${line})
 
       case ${output[0]} in
+        # first line in the output
         \#\#)
           if [[ -n ${output[1]} ]]; then
-            guessedBranched=$(guess_branch_from_hash HEAD $modulePath)
-
-            if [[ ${output[1]} == "HEAD" ]]; then
+            guessedBranched=($(guess_branch_from_hash HEAD "$modulePath"))
+            if [[ ${output[1]} == HEAD ]]; then
               MODULE_STATUS[$MS_DETACHED]=1
             fi
             if [[ ${guessedBranched} != ${stickOnBranch} ]]; then
               MODULE_STATUS[$MS_INCONSISTENT]=1
-              MODULE_STATUS[$MS_GUESSED_BRANCHES]=${guessedBranched}
+              MODULE_STATUS[$MS_GUESSED_BRANCHES]="${guessedBranched}"
             fi
             MODULE_STATUS[$MS_BRANCH_INFO]="${output[@]:1}"
           fi
-
           # TODO will not working in locale differs form en_US (or en_XX)
           # TODO git rev-list --count can help?
           if (( $remoteInteraction )); then
@@ -609,21 +628,14 @@ function module_porcelain_status() {
           fi
           ;;
         *)
-          local cmd=${output:0:2}
-          case ${cmd} in
-            \?\?)
-              MODULE_STATUS[$MS_UNTRACKED]=1
-            ;;
-            *)
-              local fChar=${cmd:0:1} sChar=${cmd:1:1}
-              [[ ${fChar} == "M" || ${sChar} == "M" ]] && MODULE_STATUS[$MS_MODIFIED]=1; MODULE_STATUS[$MS_COMMITABLE]=1
-              [[ ${fChar} == "A" || ${sChar} == "A" ]] && MODULE_STATUS[$MS_ADDED]=1; MODULE_STATUS[$MS_COMMITABLE]=1
-              [[ ${fChar} == "D" || ${sChar} == "D" ]] && MODULE_STATUS[$MS_DELETED]=1; MODULE_STATUS[$MS_COMMITABLE]=1
-              [[ ${fChar} == "R" || ${sChar} == "R" ]] && MODULE_STATUS[$MS_RENAMED]=1; MODULE_STATUS[$MS_COMMITABLE]=1
-              [[ ${fChar} == "C" || ${sChar} == "C" ]] && MODULE_STATUS[$MS_COPIED]=1; MODULE_STATUS[$MS_COMMITABLE]=1
-              [[ ${fChar} == "U" || ${sChar} == "U" ]] && MODULE_STATUS[$MS_UNMERGED]=1; MODULE_STATUS[$MS_COMMITABLE]=1
-            ;;
-          esac
+          local fChar=${line:0:1} sChar=${line:1:1}
+          [[ ${fChar} == "?" ]] && MODULE_STATUS[$MS_UNTRACKED]=$(( MODULE_STATUS[$MS_UNTRACKED] + 1 ))
+          [[ ${fChar} == M || ${sChar} == M ]] && MODULE_STATUS[$MS_MODIFIED]=$(( MODULE_STATUS[$MS_MODIFIED] + 1 )) ; MODULE_STATUS[$MS_COMMITABLE]=1
+          [[ ${fChar} == A || ${sChar} == A ]] && MODULE_STATUS[$MS_ADDED]=$(( MODULE_STATUS[$MS_ADDED] + 1 )); MODULE_STATUS[$MS_COMMITABLE]=1
+          [[ ${fChar} == D || ${sChar} == D ]] && MODULE_STATUS[$MS_DELETED]=$(( MODULE_STATUS[$MS_DELETED] + 1 )); MODULE_STATUS[$MS_COMMITABLE]=1
+          [[ ${fChar} == R || ${sChar} == R ]] && MODULE_STATUS[$MS_RENAMED]=$(( MODULE_STATUS[$MS_RENAMED] + 1 )); MODULE_STATUS[$MS_COMMITABLE]=1
+          [[ ${fChar} == C || ${sChar} == C ]] && MODULE_STATUS[$MS_COPIED]=$(( MODULE_STATUS[$MS_COPIED] + 1 )); MODULE_STATUS[$MS_COMMITABLE]=1
+          [[ ${fChar} == U || ${sChar} == U ]] && MODULE_STATUS[$MS_UNMERGED]=$(( MODULE_STATUS[$MS_UNMERGED] + 1 )); MODULE_STATUS[$MS_COMMITABLE]=1
         ;;
       esac
     done < <(git status -u --porcelain -b)
@@ -1080,7 +1092,7 @@ function _m_up() {
 
   if [[ "$doCd" == 1 ]]; then
     if [[ $(_m_git_dir) == ".git" ]]; then
-      echo "Can't up at the root module" >&2
+      echo "Can't get up at the root module" >&2
       return 1
     else
       _m_pwd 1
@@ -1211,6 +1223,99 @@ get_submodule_config () {
 }
 
 
+get_lego_setting() {
+  local section=${2:-core}
+  local               value=$( get_lego_setting_concrete "$1" "${section}" "-f .gitlego" )
+  test -z "$value" && value=$( get_lego_setting_concrete "$1" "${section}" )
+#  [[ -z value ]] || value=$( get_lego_setting_concrete $1 ${section} "--local" } )
+#  [[ -z value ]] && value=$( get_lego_setting_concrete $1 ${section} "--global"} )
+#  [[ -z value ]] && value=$( get_lego_setting_concrete $1 ${section} "--system"} )
+  echo "$value"
+}
+
+
+##
+get_lego_setting_concrete() {
+  local key="$1"
+  [[ -z $key ]] && panic "$FUNCNAME() missing setting name"
+  local file_option="${3---}"
+  local section="${2:-core}"
+  if [[ -z "${file_option##--*}" ]] && [[ ${section} == core ]] ; then
+    section=lego
+  fi
+
+  if [[ $file_option == -- ]]; then
+    unset file_option
+  fi
+
+  echo $(git config ${file_option} --get "${section:+$section.}$key") 2>/dev/null
+}
+
+get_lego_mode() {
+  local mode=$( get_lego_setting "mode")
+  if [[ -z "$mode" ]] ; then
+    mode=$( investigate_lego_mode )
+  fi
+  echo ${mode}
+}
+
+investigate_lego_mode() {
+#  echo $FUNCNAME
+  local mode
+  local ambiguous
+  local value
+
+  pushd ${cwRoot} &> /dev/null
+  if [[ -e "$cwRoot/.gitlego" ]] ; then
+    mode=versioned
+  fi
+
+  if [[  -e "${cwRoot}/.gitmodules" ]] ; then
+
+    while read module path; do
+      if [[ $(get_lego_setting_concrete "${module}.branch" "submodule" "-f .gitmodules") ]]; then
+        if (( $( check_ambiguous_mode versioned ${mode} ) )) ; then
+          mode=ambiguous
+        else
+          mode=versioned
+        fi
+        break
+      fi
+    done < <(git config -f .gitmodules --get-regexp "submodule.*.path" | sed -E "s/submodule\.(.*)\.path/\1/")
+
+    while read module value; do
+      if [[ $value == true ]] && [[ $(get_lego_setting_concrete "${module}.branch" "submodule" "--local") ]]; then
+        if (( $( check_ambiguous_mode solo ${mode} ) )) ; then
+          mode=ambiguous
+        else
+          mode=solo
+        fi
+        break
+      fi
+    done < <(git config --get-regexp "submodule.*.active" | sed -E "s/submodule\.(.*)\.active/\1/")
+
+  #else
+  #   TODO if no .gitmodules file -> no submodule -> git-lego ambigious
+  #
+  fi
+
+  popd > /dev/null
+  echo "${mode:-empty}"
+}
+
+check_ambiguous_mode() {
+  local val=$1
+  local prevVal=$2
+  if [[ -n $prevVal ]] && [[ $val != $prevVal ]] ; then
+    echo 1
+  else
+    echo 0
+  fi
+}
+
+
+
+
   ######################################################################################################################
   ############################################  MAIN SCRIPT  ###########################################################
   ######################################################################################################################
@@ -1267,12 +1372,12 @@ main() {
 	SUBACTION="default"
 
 	# Particular script can figure out a specific action depends on arguments or other circumstances.
-	# In this case it should define cmd_sub_action function and echo'ing required action.
-	# If cmd_sub_action returns empty string - default is using
-	if type "cmd_sub_action" >/dev/null 2>&1; then
-		local customized=$(cmd_sub_action "$@")
-		if [[ -n $customized ]]; then
-		  SUBACTION=$(customized)
+	# In this case it should define what_sub_action function and echo'ing required action.
+	# If what_sub_action returns empty string - default is using
+	if type "what_sub_action" >/dev/null 2>&1; then
+		local customized=$(what_sub_action "$@")
+		if [[ -n ${customized} ]]; then
+		  SUBACTION=${customized}
 		fi
 	fi
 
diff --git a/git-lego-status b/git-lego-status
--- a/git-lego-status
+++ b/git-lego-status
@@ -109,12 +109,13 @@ done
 #     $commitable - sets to 1, if one of affected module has dirty state, required to be commit
 # .
 #
-typeset info
+typeset oneLine
 
 function show_current_module_status {
-#"${subRepoPath}" "${subModule}" "${modulePath}" "${initialized}" "${stickOnBranch:--}"
+#echo "$FUNCNAME(): ${subRepoPath}" "${subModule}" "${modulePath}" "${initialized}" "${stickOnBranch:--}"
+#printf "%s,\n" "${MODULE_STATUS[@]}"
   local filePath="$1"
-  info="${3}"                  # starting with module path
+  oneLine="${3}"                  # starting with module path
   local initialized="${4:-1}"
   local stickOnBranch="$5"
 
@@ -129,81 +130,79 @@ function show_current_module_status {
 #  set -x
 
   # gather all additional fine information into $MODULE_STATUS global array
-  module_porcelain_status status ${info} "${initialized}" "${stickOnBranch}"
+  module_porcelain_status status ${oneLine} "${initialized}" "${stickOnBranch}"
 
-  # two below vars are defined to cmd_default()
+  # two below variables are defined to cmd_default()
   (( ${MODULE_STATUS[$MS_DETACHED]} )) && detached=${MODULE_STATUS[$MS_DETACHED]}
   (( ${MODULE_STATUS[$MS_COMMITABLE]} )) && commitable=${MODULE_STATUS[$MS_COMMITABLE]}
 
   typeset branchInfo=${MODULE_STATUS[$MS_BRANCH_INFO]}
-  [[ -n ${branchInfo} ]] && info+=", ${branchInfo}"
+#  local statusLine
+  [[ -n ${branchInfo} ]] && oneLine+=", ${branchInfo}"
 
   if (( ${MODULE_STATUS[$MS_UNTRACKED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="untracked"
-    infoIssues+="?"
+    verboseIssues+="${verboseIssues:+ ,}untracked (${MODULE_STATUS[$MS_UNTRACKED]} files)"
+    infoIssues+="?x${MODULE_STATUS[$MS_UNTRACKED]}"
   fi
   if (( ${MODULE_STATUS[$MS_ADDED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="added"
-    infoIssues+="A"
+    verboseIssues+="${verboseIssues:+ ,}added (${MODULE_STATUS[$MS_ADDED]} files)"
+    infoIssues+="${infoIssues:+, }Ax${MODULE_STATUS[$MS_ADDED]}"
+
   fi
   if (( ${MODULE_STATUS[$MS_MODIFIED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="modified"
-    infoIssues+="M"
+    verboseIssues+="${verboseIssues:+ ,}modified (${MODULE_STATUS[$MS_MODIFIED]} files)"
+    infoIssues+="${infoIssues:+, }Mx${MODULE_STATUS[$MS_MODIFIED]}"
   fi
   if (( ${MODULE_STATUS[$MS_DELETED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="deleted"
-    infoIssues+="D"
+    verboseIssues+="${verboseIssues:+ ,}deleted (${MODULE_STATUS[$MS_DELETED]} files)"
+    infoIssues+="${infoIssues:+, }Dx${MODULE_STATUS[$MS_DELETED]}"
   fi
   if (( ${MODULE_STATUS[$MS_RENAMED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="renamed"
-    infoIssues+="R"
+    verboseIssues+="${verboseIssues:+ ,}renamed (${MODULE_STATUS[$MS_RENAMED]} files)"
+    infoIssues+="${infoIssues:+, }Rx${MODULE_STATUS[$MS_RENAMED]}"
   fi
   if (( ${MODULE_STATUS[$MS_COPIED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="copied"
-    infoIssues+="C"
+    verboseIssues+="${verboseIssues:+ ,}copied (${MODULE_STATUS[$MS_COPIED]} files)"
+    infoIssues+="${infoIssues:+, }Cx${MODULE_STATUS[$MS_COPIED]}"
   fi
   if (( ${MODULE_STATUS[$MS_UNMERGED]} )); then
-    (( ${#verboseIssues} )) && verboseIssues+=", "
-    verboseIssues+="unmerged"
-    infoIssues+="U"
+    verboseIssues+="${verboseIssues:+ ,}unmerged (${MODULE_STATUS[$MS_UNMERGED]} files)"
+    infoIssues+="${infoIssues:+, }Ux${MODULE_STATUS[$MS_UNMERGED]}"
   fi
 
+
 #  set -x
-  if [[ ${MODULE_STATUS[$MS_UNINITIALIZED]} == 1 ]]; then
-    info+=", not initialized"
+  if (( ${MODULE_STATUS[$MS_UNINITIALIZED]} )); then
+    oneLine+=", not initialized"
     verboseMsg+=("The module not initialized yet. 'git-lego init --reconcile' to fix it.")
-    print_if_expected
+    print_consistent_status
   else
+    if (( ${MODULE_STATUS[$MS_DETACHED]} )); then
+      oneLine+=", detached"
+      verboseMsg+=("You need to run either 'git-lego checkout <branch-name>' or 'git-lego init [--reconcile|--pin]' to make those consent.")
+    fi
+#    set -x
+    if (( ${MODULE_STATUS[$MS_INCONSISTENT]} )) ; then
+      oneLine+=", not matched"
+      if [[ -n ${MODULE_STATUS[$MS_INNER_REV_HINT]} ]] ; then
+        verboseMsg+=("Module has inconsistent state, outer module expects ${MODULE_STATUS[$MS_INNER_REV_HINT]}, which the module")
+      else
+        verboseMsg+=("Module has inconsistent state, outer module expects  ")
+      fi
+    fi
+#    set +x
+    print_consistent_status ${MODULE_STATUS[$MS_INCONSISTENT]} ${MODULE_STATUS[$MS_DETACHED]}
+    if [[ -n ${MODULE_STATUS[$MS_GUESSED_BRANCHES]} ]] && (( ${MODULE_STATUS[$MS_DETACHED]} )) ; then
+      oneLine+=", possible: ${MODULE_STATUS[$MS_GUESSED_BRANCHES]}"
+#        verboseMsg+=("Module has discrepancy between its current state and revision, which outer module expected")
+    fi
     if (( ${#infoIssues} )) ; then
       verboseIssues="issues: "$verboseIssues" paths"
       verboseMsg+=("${verboseIssues}")
-      info+=", dirty: "${infoIssues}
-    else
-      if [[ ${MODULE_STATUS[$MS_DETACHED]} == 1 ]] ; then
-        info+=", detached"
-        verboseMsg+=("You need to run either 'git-lego checkout <branch-name>' or 'git-lego init [--reconcile|--pin]' to make those consent.")
-      fi
-      if [[ ${MODULE_STATUS[$MS_INCONSISTENT]} == 1 ]] ; then
-        info+=", not consistent"
-        verboseMsg+=("Module has discrepancy between its current state and revision, which outer module expected")
-      fi
-      print_if_expected ${MODULE_STATUS[$MS_INCONSISTENT]}
-      if [[ -n ${MODULE_STATUS[$MS_GUESSED_BRANCHES]} ]] ; then
-        info+=", possible: ${MODULE_STATUS[$MS_GUESSED_BRANCHES]}"
-#        verboseMsg+=("Module has discrepancy between its current state and revision, which outer module expected")
-      fi
-      if (( ${MODULE_STATUS[$MS_INCONSISTENT]} )) ; then
-        info+=")"
-      fi
+      oneLine+=", dirty: "${infoIssues}
     fi
   fi
-  verboseMsg[0]=${info}
+  verboseMsg[0]=${oneLine}
 #  set +x
   cw_echo "${verboseMsg[@]}"
 
@@ -212,17 +211,18 @@ function show_current_module_status {
   fi
 }
 
-print_if_expected() {
-  if (( $1 )) ; then
-    info+=" ("
-  else
-    if [[ -n ${MODULE_STATUS[$MS_INNER_REV_HINT]} ]]; then
-      info+=", "
-    fi
+print_consistent_status() {
+  local isOK=1
+  if (( ${2:-0} )) || (( ${1:-0} )); then
+    isOK=0
   fi
-  info+="expected:${MODULE_STATUS[$MS_INNER_REV_HINT]:-no hint}"
-  if [[ -n ${MODULE_STATUS[$MS_INNER_REV_HINT]} ]]; then
-    verboseMsg+=("Expected, that module should be initialized to ${MODULE_STATUS[$MS_INNER_REV_HINT]} revision")
+  if (( ! $isOK )); then
+    oneLine+=", expected:${MODULE_STATUS[$MS_INNER_REV_HINT]:-no hint}"
+  else
+    oneLine+=", OK"
+  fi
+  if (( ! $isOK )) && [[ -n ${MODULE_STATUS[$MS_INNER_REV_HINT]} ]]; then
+    verboseMsg+=("Expected, that module should be initialized to ${MODULE_STATUS[$MS_INNER_REV_HINT]}")
   fi
 }
 
@@ -231,14 +231,12 @@ function status_level() {
   [[ -z ${levelPath} ]] && panic "$FUNCNAME()... parameter 'path' is required"
   local repoBranch
   local ret=0   # return code, 0 - the repo is syncronized
-  local childRet=${asdf} # child return code
+  local childRet # child return code
   local stickOnBranch=${5:--}
 
-#  set -x
   drop_to_affected ${levelPath}
 
   (( ! $? )) && show_current_module_status "$@"
-#  set +x
 
   if [ -f .gitmodules ]; then
     while read -a module; do
@@ -297,7 +295,7 @@ cmd_default() {
     cw_cr
     cw_echo "${msg}"
     [[ -n ${msg2} ]] && cw_echo "${msg2}"
-    (( ! $verbose )) && cw_echo "${FLAGS_PREFIX} -v ... option to get output more verbose or ${FLAGS_PREFIX} --help for other options"
+    (( ! $verbose )) && cw_echo "'${FLAGS_PREFIX} -v ' option to get output more verbose or '${FLAGS_PREFIX} --help for other options'"
     cw_cr
   fi
 
